Updated Woomera and Kourou statics, added new configs for Harrier and KNES parts in 002_AdditionalConfigs
TheBeardyPenguin/ForAllKerbalkind pull request #3
Opened 2024-09-14 13:30 UTC by ChrisRaynerSG

<h1><b>Hopefully Woomera wont change its grass colour anymore</b></h1>

2024-09-20 13:33 UTC, TheBeardyPenguin commented
Knes config needs more work.
My painstaking costing has been removed and there is now overlap with the RealismOverhaul SuggestedMods Knes config, particularly for Hermes. That config should take priority everywhere there is overlap.

2024-09-20 13:34 UTC, TheBeardyPenguin requested changes
Knes config needs more work.
My painstaking costing has been removed and there is now overlap with the RealismOverhaul SuggestedMods Knes config, particularly for Hermes. That config should take priority everywhere there is overlap.

2024-09-20 13:50 UTC, TheBeardyPenguin commented
Instead of my workaround using identical parts, I recommend replacing with the approach used in **RP-0/Tree/ECM-Parts.cfg** and  **RP-0/Tree/EntryCostModifiers.cfg**.
Use **@ENTRYCOSTMODS:FOR[RP-0]** to create a new unique cost modifier for each crewed vehicle, set to the total cost I previously had each part set to.
Then use **@ENTRYCOSTMODS:FOR[xxxRP-0]** to assign all the parts on the vehicle to that cost modifier, so when you buy one part it makes the rest of them free. You can add extra costs on top with a comma separated list of multiple ECMs, or just a fixed number if you want to.
It's somewhat explained in section 3.3 of this page https://en.namu.wiki/w/RP-1/자주%20묻는%20질문

2024-10-14 07:26 UTC, ChrisRaynerSG commented
RP-0 configs for knes parts changed back to use old identical parts system, and now use @ENTRYCOSTMODS:FOR[RP-0] as mentioned in previous message

2024-10-14 14:30 UTC, TheBeardyPenguin commented on GameData/002_AdditionalConfigs/Knes.cfg
> +	ESA-mk1-capsule = ESA-mk1-LES, 75000
This needs to be moved to after ESA-mk1-LES is defined, two lines later.

2024-10-14 14:30 UTC, TheBeardyPenguin commented on GameData/002_AdditionalConfigs/Knes.cfg
> +	//MRK parts
All underscores in part names have to be replaced with dashes '-' or the modifier won't be applied.

2024-10-14 14:32 UTC, TheBeardyPenguin commented on GameData/002_AdditionalConfigs/Knes.cfg
> +	%identicalParts = _Knes_Control_LowProfile_RCS_0625,Knes_DockingPortJr_0625,Knes_Parachute_Inline_0625,Knes_Crew_Pod_09375
This was only a workaround when I didn't know how entry cost modifiers worked. Now that the parts are properly costed, all of these identicalParts declarations can just be deleted. It should only be used for actual identical parts, for example Gemini capsules added by two different mods. There is no need for its usage in Knes

2024-10-14 14:33 UTC, TheBeardyPenguin commented on GameData/002_AdditionalConfigs/Knes.cfg
> +	%identicalParts = _Knes_Control_LowProfile_RCS_0625,Knes_DockingPortJr_0625,Knes_Parachute_Inline_0625,Knes_Service_Module_Viking_09375
Delete this.

2024-10-14 14:36 UTC, TheBeardyPenguin requested changes
Delete identicalParts tags as they were simply a workaround before the entry cost modifiers were understood.
Replace underscores with dashes in entry cost modifier names, even when parts names containing underscores are being referenced (it's weird I know).
Remove overlap with GameData/RealismOverhaul/SuggestedMods/Knes configs, namely Hermes and MRC mass etc.

2024-10-18 13:49 UTC, TheBeardyPenguin commented on GameData/002_AdditionalConfigs/Knes.cfg
> -	%capsuleTier = Mature
Kerbalism science experiments and storage aren't configured by the RO configs! Shouldn't have removed this!

2025-02-23 11:41 UTC, TheBeardyPenguin approved these changes
If the Viking docking port isn't scaling properly, I suggest changing @rescaleFactor to %rescaleFactor, as it may not have an existing rescaleFactor to change.
If that fails, try changing the hook to :AFTER[RealismOverhaul]

Speaking of hooks, some of your changes are being overridden by RealismOverhaul/RO_SuggestedMods/Knes/KNES_Core.cfg

Finally in your Knes entry cost mods you refer to ESA-mk1-LES which I can't find defined anywhere, is that a mistake?

I'll approve the PR though since these are just minor issues you may or may not want to resolve.

2025-02-23 11:42 UTC, merged